config/routes.rb
Rails.application.routes.draw do
  resources :flats
  devise_for :users, :controllers => { registrations: 'users/registrations' }

  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "my-account", to: "pages#profile"
  get "search", to: "pages#search"
  # Defines the root path route ("/")
  # root "articles#index"
  resources :restaurants do
    resources :reviews, only: [:index, :new, :create]
    resources :favourites, only: [:new, :create]
  end
  resources :users, only: %i[show update] do
    resources :friends, only: %i[index new create show]
    resources :followers, only: %i[index]
    resources :favourites, only: [:show, :index]
    get "restaurants", to: "restaurants#restaurants"
    get "friends-fave", to:"friends#favourites"
  end
  resources :friends, only: [:destroy]
  resources :reviews, only: %i[show edit update]
  resources :favourites, only: [:destroy]
  resources :collections, only: [:destroy]
end

app/models/user.rb
include PgSearch::Model

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # has_many :friends, class_name: 'Friend', foreign_key: 'followee_id, follower_id'

  has_many :follower_relationships, foreign_key: :followee_id, class_name: 'Friend'
  has_many :followers, through: :follower_relationships, source: :follower
  has_many :followee_relationships, foreign_key: :follower_id, class_name: 'Friend'
  has_many :followees, through: :followee_relationships, source: :followee

  has_one_attached :photo
  has_many :restaurant

  validates :name, presence: true
  validates :role, presence: true
  has_many :restaurants
  has_many :reviews

  pg_search_scope :global_search,
  against: [:name, :description],
  using: {
    tsearch: { prefix: true }
  }
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    if params[:user][:role] === "regular"
      @restaurant = Restaurant.all
      @restaurant.each do |rest|
        @collection = Collection.new
        @collection.restaurant = rest
        @collection.user = current_user
        if @collection.save
        else
          render :new, status: :unprocessable_entity
        end
      end
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:role])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:description])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show update]

  def show
    @tab = 5
    @title = "User Profile"
    @friend = Friend.new
    @following = Friend.where(follower_id: @user.id)
    @followers = Friend.where(followee_id: @user.id)
    @favourites = Favourite.where(user_id: @user)
    @restaurants = Restaurant.where(user_id: @user)
    if user_signed_in?
      @current_user_friends = Friend.where(follower_id: current_user.id)
      @current_user_friends_users = []
      @current_user_friends.each do |friend|
        @current_user_friends_users << User.find(friend.followee_id).id
      end
      @current_friend = Friend.find_by(follower_id: current_user.id, followee_id: @user.id)
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
    end
  end

  private

  def user_params
    params.require(:user).permit(:photo)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/show.html.erb
<div class="profile-container" data-controller="add-profile-image">
  <div class="profile-top d-flex flex-column">
      <% if user_signed_in? && current_user.id != @user.id %>
        <div class="profile-header d-flex flex-column">
          <div class="profile-image">
            <% if @user.photo.attached? %>
              <%= cl_image_tag @user.photo.key, width: 150, height: 150, crop: :thumb, gravity: :face, :class => 'profile-pic' %>
              <% else %>
              <div class='no-profile'>
              <i class="fa-solid fa-user"></i>
              </div>
            <% end %>
          </div>
          <div class="mt-1">
            <h3 class='username'><%= @user.name %></h3>
          </div>
        </div>
      <% else %>
        <div class="profile-header">
          <div class="profile-image" data-action="click->add-profile-image#show">
            <% if @user.photo.attached? %>
              <%= cl_image_tag @user.photo.key, width: 150, height: 150, crop: :thumb, gravity: :face, :class => 'profile-pic' %>
              <% else %>
              <div class='no-profile'>
              <i class="fa-solid fa-user"></i>
              </div>
            <% end %>
          </div>
          <div class="mt-1">
            <h3 class='username'><%= @user.name %></h3>
          </div>
        </div>
      <% end %>

      <% if current_user.role == "regular" %>
        <div class="follow-btns mb-3">
          <% if user_signed_in? && current_user.id != @user.id %>
            <% if @current_user_friends_users.include?(@user.id) %>
                <%= link_to 'Following',
                    friend_path(@current_friend),
                    data: {turbo_method: :delete}, :class => 'unfollow-btn'%>
              <% else %>
                <%= simple_form_for [@user, @friend] do |f| %>
                <%= f.submit 'Follow', :class => 'follow-btn' %>
              <% end %>
            <% end %>
          <% end %>
        </div>

        <div class="follow-container">
          <div class="follow-info">
            <h3 class="follow-title">Following</h3>
            <div class="follow-count">
              <%= link_to @following.count, user_friends_path(@user), :class => 'follow-count-text' %>
            </div>
          </div>
          <div class="follow-info">
            <h3 class="follow-title">Followers</h3>
            <div class="follow-count">
              <%= link_to @followers.count, user_followers_path(@user), :class => 'follow-count-text' %>
            </div>
          </div>
        </div>
      </div>
    <% end %>

    <%# profile image form %>
    <% if user_signed_in? && @user == current_user %>
      <div class="add-photo-form d-none" data-add-profile-image-target='form'>
        <%= simple_form_for(@user) do |f| %>
          <%= f.input :photo, as: :file %>
          <%= f.submit 'Add Image', :class => 'add-btn' %>
        <% end %>
      </div>
    <% end %>
    <%# end of profile image form %>
</div>

<div class="profile-info">
    <% if @user.role == "regular" %>
      <div class="favourites">
        <h3>Favourites</h3>
          <div class="fav-container">
            <% @favourites.each do |favourite| %>
              <div class="container-colour">
                <% restaurant = Restaurant.find_by(id: favourite.restaurant_id) %>
                <% if restaurant.photo.attached? %>
                  <%= cl_image_tag restaurant.photo.key, :class => "image-show-container" %>
                <% else %>
                  <div class="no-image">
                    <h2>No Image</h2>
                  </div>
                <% end %>
                <p id="test"><%= link_to restaurant.name, restaurant_path(restaurant.id) %></p>
              </div>
            <% end %>
          </div>
      </div>
    <% elsif @user.role == "owner" %>
      <div class="restaurants">
        <h3>Restaurants</h3>
          <div class="fav-container">
            <% @restaurants.each do |restaurant| %>
              <div class="container-colour">
                <% rest = Restaurant.find_by(id: restaurant.id) %>
                <% if rest.photo.attached? %>
                  <%= cl_image_tag rest.photo.key, :class => "image-show-container" %>
                <% else %>
                  <div class="no-image">
                    <h2>No Image</h2>
                  </div>
                <% end %>
                <p id="test"><%= link_to rest.name, restaurant_path(rest.id) %></p>
              </div>
            <% end %>
          </div>
      </div>
    <% end %>
</div>