config/routes.rb
Rails.application.routes.draw do
  resources :flats
  devise_for :users, :controllers => { registrations: 'users/registrations' }

  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "my-account", to: "pages#profile"
  get "search", to: "pages#search"
  # Defines the root path route ("/")
  # root "articles#index"
  resources :restaurants do
    resources :reviews, only: [:index, :new, :create]
    resources :favourites, only: [:new, :create]
  end
  resources :users, only: %i[show update] do
    resources :friends, only: %i[index new create show]
    resources :followers, only: %i[index]
    resources :favourites, only: [:show, :index]
    get "restaurants", to: "restaurants#restaurants"
    get "friends-fave", to:"friends#favourites"
  end
  resources :friends, only: [:destroy]
  resources :reviews, only: %i[show edit update]
  resources :favourites, only: [:destroy]
  resources :collections, only: [:destroy]
end

app/views/shared/_navbar.html.erb
<div class="navbar fixed-bottom">
  <div class="container-fluid d-flex justify-content-around">
    <% if user_signed_in? && current_user.role == "owner" %>
      <%# My Restaurant Link %>
      <div class="nav-item d-flex flex-column justify-content-center align-items-center">
        <% if @tab == 1 %>
          <%= link_to user_restaurants_path(current_user.id) do %>
            <div class="nav-item-icon flex-grow-1 active-tab">
              <i class="fa-solid fa-utensils"></i>
            </div>
            <div class="nav-item-text mb-1 active-tab">
              Restaurants
            </div>
          <% end %>
        <% else %>
          <%= link_to user_restaurants_path(current_user.id) do %>
            <div class="nav-item-icon flex-grow-1 inactive-tab">
              <i class="fa-solid fa-utensils"></i>
            </div>
            <div class="nav-item-text mb-1 inactive-tab">
              Restaurants
            </div>
          <% end %>
        <% end %>
      </div>

      <%# Add Restaurant Link %>
      <div class="nav-item d-flex flex-column justify-content-center align-items-center">
        <% if @tab == 2 %>
          <%= link_to new_restaurant_path do %>
            <div class="nav-item-icon flex-grow-1 active-tab">
              <i class="fa-solid fa-plus"></i>
            </div>
            <div class="nav-item-text mb-1 active-tab">
              Add
            </div>
          <% end %>
        <% else %>
          <%= link_to new_restaurant_path do %>
            <div class="nav-item-icon flex-grow-1 inactive-tab">
              <i class="fa-solid fa-plus"></i>
            </div>
            <div class="nav-item-text mb-1 inactive-tab">
              Add
            </div>
          <% end %>
        <% end %>
      </div>

      <%# Profile Link %>
      <div class="nav-item d-flex flex-column justify-content-center align-items-center">
        <% if @tab == 5 %>
          <%= link_to user_path(current_user) do %>
            <div class="nav-item-icon flex-grow-1 active-tab">
              <i class="fa-solid fa-user" id="nav-user"></i>
            </div>
            <div class="nav-item-text mb-1 active-tab">
              Profile
            </div>
          <% end %>
        <% else %>
          <%= link_to user_path(current_user) do %>
            <div class="nav-item-icon flex-grow-1 inactive-tab">
              <i class="fa-solid fa-user inactive-tab" id="nav-user"></i>
            </div>
            <div class="nav-item-text mb-1 inactive-tab">
              Profile
            </div>
          <% end %>
        <% end %>
      </div>

    <% elsif user_signed_in? %>
      <%# All Restaurants Link %>
      <div class="nav-item d-flex flex-column justify-content-center align-items-center">
      <% if @tab == 1 %>
        <%= link_to restaurants_path do %>
            <div class="nav-item-icon flex-grow-1 active-tab">
              <i class="fa-solid fa-utensils"></i>
            </div>
            <div class="nav-item-text mb-1 active-tab">
              All
            </div>
          <% end %>
      <% else %>
        <%= link_to restaurants_path do %>
          <div class="nav-item-icon flex-grow-1 inactive-tab">
            <i class="fa-solid fa-utensils"></i>
          </div>
          <div class="nav-item-text mb-1 inactive-tab">
            All
          </div>
        <% end %>
      <% end %>
      </div>
      <%# Search Link %>
      <div class="nav-item d-flex flex-column justify-content-center align-items-center">
      <% if @tab == 2 %>
        <%= link_to search_path do %>
          <div class="nav-item-icon flex-grow-1 active-tab">
            <i class="fa-solid fa-magnifying-glass"></i>
          </div>
          <div class="nav-item-text mb-1 active-tab">
            Search
          </div>
        <% end %>
      <% else %>
        <%= link_to search_path do %>
          <div class="nav-item-icon flex-grow-1 inactive-tab">
            <i class="fa-solid fa-magnifying-glass"></i>
          </div>
          <div class="nav-item-text mb-1 inactive-tab">
            Search
          </div>
        <% end %>
      <% end %>
      </div>
      <%# Home Link %>
      <div class="nav-item d-flex flex-column justify-content-center align-items-center">
        <%= link_to root_path, class: "home-btn" do %>
          <div class="nav-item-icon flex-grow-1">
            <img src="https://res.cloudinary.com/heefang/image/upload/v1661357606/yum_icon_white_xa7lyn.png">
          </div>
        <% end %>
      </div>
      <%# Favourites Link %>
      <div class="nav-item d-flex flex-column justify-content-center align-items-center">
      <% if @tab == 4 %>
        <%= link_to user_favourites_path(current_user) do %>
          <div class="nav-item-icon flex-grow-1 active-tab">
            <i class="fa-solid fa-heart"></i>
          </div>
          <div class="nav-item-text mb-1 active-tab">
            Faves
          </div>
        <% end %>
      <% else %>
        <%= link_to user_favourites_path(current_user) do %>
          <div class="nav-item-icon flex-grow-1 inactive-tab">
            <i class="fa-solid fa-heart"></i>
          </div>
          <div class="nav-item-text mb-1 inactive-tab">
            Faves
          </div>
          <% end %>
      <% end %>
      </div>
      <%# Profile Link %>
      <div class="nav-item d-flex flex-column justify-content-center align-items-center">
      <% if @tab == 5 %>
        <%= link_to user_path(current_user) do %>
          <div class="nav-item-icon flex-grow-1 active-tab">
            <i class="fa-solid fa-user" id="nav-user"></i>
          </div>
          <div class="nav-item-text mb-1 active-tab">
            Profile
          </div>
        <% end %>
      <% else %>
        <%= link_to user_path(current_user) do %>
          <div class="nav-item-icon flex-grow-1 inactive-tab">
            <i class="fa-solid fa-user inactive-tab" id="nav-user"></i>
          </div>
          <div class="nav-item-text mb-1 inactive-tab">
            Profile
          </div>
        <% end %>
      <% end %>
      </div>

      <% else %>
      <%# All Restaurants Link %>
      <div class="nav-item d-flex flex-column justify-content-center align-items-center">
        <%= link_to restaurants_path do %>
          <div class="nav-item-icon flex-grow-1">
            <i class="fa-solid fa-utensils"></i>
          </div>
          <div class="nav-item-text mb-1">
            All
          </div>
        <% end %>
      </div>
      <%# Search Link %>
      <div class="nav-item d-flex flex-column justify-content-center align-items-center">
        <%= link_to search_path do %>
          <div class="nav-item-icon flex-grow-1">
            <i class="fa-solid fa-magnifying-glass"></i>
          </div>
          <div class="nav-item-text mb-1">
            Search
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_topnav.html.erb
<div class="navbar sticky-top">
  <div class="back-button">
  <span><%= link_to icon('fa-solid', 'arrow-left'), :back %></span>
  </div>
  <div class="title">
    <span><%= @title %></span>
  </div>
  <% if user_signed_in? %>
    <div>
      <span>
        <button type="button" class="logout-btn" data-bs-toggle="modal" data-bs-target="#logoutModal">
            <i class="fa-solid fa-right-from-bracket"></i>
        </button>
      </span>
    </div>
  <% else %>
    <div class="logout-btn">
      <span><%= link_to icon('fa-solid', 'arrow-right-to-bracket'), new_user_session_path %></span>
    </div>
  <% end %>
</div>

<%# logout prompt %>

<div class="modal fade" id="logoutModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Log Out</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure you want to log out?
      </div>
      <div class="modal-footer">
        <%= button_to("Yes", destroy_user_session_path, method: :delete, :class => 'btn btn-primary') %>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
      </div>
    </div>
  </div>
</div>