config/routes.rb
Rails.application.routes.draw do
  resources :flats
  devise_for :users, :controllers => { registrations: 'users/registrations' }

  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "my-account", to: "pages#profile"
  get "search", to: "pages#search"
  # Defines the root path route ("/")
  # root "articles#index"
  resources :restaurants do
    resources :reviews, only: [:index, :new, :create]
    resources :favourites, only: [:new, :create]
  end
  resources :users, only: %i[show update] do
    resources :friends, only: %i[index new create show]
    resources :followers, only: %i[index]
    resources :favourites, only: [:show, :index]
    get "restaurants", to: "restaurants#restaurants"
    get "friends-fave", to:"friends#favourites"
  end
  resources :friends, only: [:destroy]
  resources :reviews, only: %i[show edit update]
  resources :favourites, only: [:destroy]
  resources :collections, only: [:destroy]
end

app/models/restaurant.rb
include PgSearch::Model

class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  belongs_to :user
  has_one_attached :photo
  has_many :collections, dependent: :destroy
  has_many :favourites, dependent: :destroy

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  pg_search_scope :global_search,
    against: [:name, :address, :cuisine, :description],
  using: {
    tsearch: { prefix: true }
  }
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def show
    @title = "Restaurant Details"
    @restaurant = Restaurant.find(params[:id])
    @reviews = Review.where(restaurant_id: @restaurant)
    if user_signed_in?
      if @restaurant.favourites.find_by(user_id: current_user.id).nil?
        @favourite = Favourite.new
      else
        @favourite = Favourite.find_by(user_id: current_user.id, restaurant_id: @restaurant.id)
      end
    end
    @ratings = []
    @restaurant.reviews.each do |review|
      @ratings << review.rating
    end
    if @ratings.count.positive?
      @avg_rating = (@ratings.sum / @ratings.count).round(1)
    else
      @avg_rating = "No ratings yet"
    end
    @review = Review.new

    @markers =
      [{
        lat: @restaurant.latitude,
        lng: @restaurant.longitude,
        info_window: render_to_string(partial: "info_window", locals: { restaurant: @restaurant })
      }]
  end

  def index
    @title = "All Restaurants"
    @tab = 1
    @restaurants = Restaurant.all
    @rest_rating = {}

    @restaurants.each do |rest|
      @ratings = []
      rest.reviews.each do |review|
        @ratings << review.rating
      end
      if @ratings.count.positive?
        @avg_rating = @ratings.sum.fdiv(@ratings.count).round(1)
        @rest_rating[rest.id]= @avg_rating
      else
        @avg_rating = "No ratings yet"
      end
    end
  end

  def new
    @tab = 2
    @title = "Add a Restaurant"
    @restaurant = Restaurant.new
  end

  def restaurants
    @tab = 1
    @title = "My Restaurants"
    @restaurants = Restaurant.where(user_id: params[:user_id])
    @rest_rating = {}

    @restaurants.each do |rest|
      @ratings = []
      rest.reviews.each do |review|
        @ratings << review.rating
      end
      if @ratings.count.positive?
        @avg_rating = @ratings.sum.fdiv(@ratings.count).round(1)
        @rest_rating[rest.id]= @avg_rating
      else
        @avg_rating = "No ratings yet"
      end
    end
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user = current_user
    @user = User.all
    if @restaurant.save
      @user.each do |user|
        if user.role === "regular"
          @collection = Collection.new
          @collection.restaurant = @restaurant
          @collection.user = user
          if @collection.save
          else
            render :new, status: :unprocessable_entity
          end
        end
      end
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy
    redirect_to user_restaurants_path(current_user), status: :see_other
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :cuisine, :description, :photo)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/views/restaurants/_form.html.erb
<%= simple_form_for(restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :cuisine %>
  <%= f.input :description %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/restaurants/_info_window.erb
<h2><%= restaurant.name %></h2>
<p><%= restaurant.address %></p>

app/views/restaurants/_restaurant_card.html.erb
<div class="card">
  <div>
    <div class="card-image">
      <% if restaurant.photo.attached? %>
        <%= cl_image_tag restaurant.photo.key, :class => "image-show" %>
      <% else %>
        <img src="https://res.cloudinary.com/dswoabunp/image/upload/v1659754023/samples/food/dessert.jpg"/>
      <% end %>
    </div>
    <div class="card-body">
      <h6 class="card-name"><%= restaurant.name %></h6>
      <% ratings = [] %>
      <% restaurant.reviews.each do |review| %>
      <% ratings << review.rating %>
      <% end %>
      <% if ratings.count.positive? %>
        <% avg_rating = (ratings.sum / ratings.count).round(1) %>
      <% else %>
        <% avg_rating = "No ratings yet" %>
      <% end %>
      <div class="card-rating">
        <h6>Rating:</h6>
        <% if avg_rating == "No ratings yet" %>
          <p><%= avg_rating %></p>
        <% else %>
          <p><%= avg_rating %></p>
          <div class="flex gap-x-1 mb-2 card-stars">
            <% Review::MAX_RATING.times do |n| %>
            <%= inline_svg_tag("star.svg",
              class: "review-star #{star_rating_class(avg_rating, n)}") %>
            <% end %>
          </div>
        <% end %>
    </div>
    <div class="card-icons">
    <i class="fa-solid fa-circle-xmark"></i>
    <div class="heart-circle">
      <i class="fa-solid fa-heart card-heart"></i>
    </div>
    </div>
  </div>
</div>
<div class="choice d-none">
    <%= simple_form_for [restaurant, @favourite], defaults: { input_html: { class: 'collection-fave' } } do |f| %>
      <%= f.input :restaurant_id, input_html: { value: restaurant }, as: :hidden  %>
      <%= f.input :user_id, input_html: { value: current_user.id }, as: :hidden  %>
      <%= f.input :location, input_html: { value: "home" }, as: :hidden  %>
        <%= button_tag(type: 'submit', class:"fav-button collection-fave-btn d-none") do %>
          <i class="fa-solid fa-heart home-heart"></i>
        <% end %>
    <% end %>
    <%= link_to icon("fa", "play"),
      collection_path(restaurant),
      data: {'turbo_method': :delete}, :class => "collection-del-btn d-none"
    %>
</div>
</div>

app/views/restaurants/_restaurant_popup.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                  <div class="modal-header">
                    <h4 class="modal-title" id="exampleModalLabel"><%= restaurant.name %></h4>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    <div class="home-restaurant-details">
                      <h6>Rating:</h6>
                          <% ratings = [] %>

                          <% restaurant.reviews.each do |review| %>
                            <% ratings << review.rating %>
                          <% end %>

                          <% if ratings.count.positive? %>
                            <% avg_rating = (ratings.sum / ratings.count).round(1) %>
                            <div class="home-rating-details">
                              <p class="home-rating"><%= avg_rating %></p>
                              <div class="flex gap-x-3 mb-4 home-stars">
                                  <% Review::MAX_RATING.times do |n| %>
                                    <%= inline_svg_tag("star.svg",
                                      class: "review-star w-8 h-8 #{star_rating_class(avg_rating, n)}") %>
                                  <% end %>
                              </div>
                            </div>
                          <% else %>
                            <p class="home-modal-details"><%= "No ratings yet" %></p>
                          <% end %>
                      <h6>Cuisine:</h6>
                      <p class="home-modal-details"><%= restaurant.cuisine %></p>
                      <h6>Description: </h6>
                      <p class="home-modal-details"><%= restaurant.description %></p>
                      <h6>Location: </h6>
                      <p class="home-modal-details"><%= restaurant.address %></p>
                    </div>
                    <%= link_to 'View More', restaurant_path(restaurant), :class => 'home-view-btn' %>
                  </div>
                  <%# <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                  </div> %>
                </div>
              </div>
            </div>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>
<%= render "form", restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<div class="card-category">
  <div class="content">
    <% @restaurants.each do |restaurant| %>
      <div class="cards">
        <% if restaurant.photo.attached? %>
          <%= link_to restaurant_path(restaurant) do %>
            <%= cl_image_tag restaurant.photo.key, :class => "image-show" %>
          <% end %>
        <% else %>
          <div class="no-image">
            <h2>No Image</h2>
          </div>
        <% end %>
        <h4><b><%= link_to restaurant.name, restaurant_path(restaurant)  %></b></h4>
        <% if @rest_rating[restaurant.id].nil? %>
          <div class="card-rating"><h5><b> No ratings yet</b></h5></div>
        <% else %>
          <div class="card-rating"><h5><b>Rating: </b><%= @rest_rating[restaurant.id] %> &nbsp</h5>
            <div class="flex gap-x-1 mb-2 card-stars">
              <% Review::MAX_RATING.times do |n| %>
                <%# <%= <i class="fa-light fa-star #{star_rating_class(@avg_rating, n)}"></i> %>
                <%= inline_svg_tag("star.svg",
                  class: "review-star w-8 h-8 #{star_rating_class(@rest_rating[restaurant.id], n)}") %>
              <% end %>
            </div>
          </div>
        <% end %>
          <p id="overflow-hidden"><%= restaurant.description %><br><%= link_to "Find out more!", restaurant_path(restaurant) %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/new.html.erb
<%= render "form", restaurant: @restaurant %>

app/views/restaurants/restaurants.html.erb
<div class="card-category">
  <div class="content">
    <% @restaurants.each do |restaurant| %>
      <div class="cards">
        <% if restaurant.photo.attached? %>
          <%= link_to restaurant_path(restaurant) do %>
            <%= cl_image_tag restaurant.photo.key, :class => "image-show" %>
          <% end %>
          <h4><b><%= link_to restaurant.name, restaurant_path(restaurant)  %></b></h4>
              <% if @rest_rating[restaurant.id].nil? %>
                <div class="card-rating"><h5><b>No ratings yet</b></h5></div>
              <% else %>
                <div class="card-rating"><h5><b>Rating: </b><%= @rest_rating[restaurant.id]  %> &nbsp</h5>
                  <div class="flex gap-x-1 mb-2">
                      <% Review::MAX_RATING.times do |n| %>
                        <%# <%= <i class="fa-light fa-star #{star_rating_class(@avg_rating, n)}"></i> %>
                        <%= inline_svg_tag("star.svg",
                          class: "review-star w-8 h-8 #{star_rating_class(@rest_rating[restaurant.id], n)}") %>
                      <% end %>
                  </div>
                </div>
              <% end %>
          <p id="overflow-hidden"><%= restaurant.description %><br><%= link_to "Find out more!", restaurant_path(restaurant) %></p>
        <% else %>
          <%= "" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="card-category">
  <% if @restaurant.photo.attached? %>
    <%= cl_image_tag @restaurant.photo.key, :class => "image-show" %>
  <% else %>
    <div class="no-image">
      <h2>No Image</h2>
    </div>
  <% end %>
  <div class="restaurant-infos">
    <div>
      <div class="restaurant-details">
        <div class="restaurant-title-block d-flex justify-content-between">
          <div class="restaurant-title mt-3"><h1><%= @restaurant.name %></h1></div>
          <%# Show Bookmark buttons if user is signed in %>
          <% if user_signed_in? %>
            <div class="bookmark">
              <% if @restaurant.favourites.find_by(user_id: current_user.id) == nil %>
                <%= render "favourites/form", favourite: @favourite %>
              <% else %>
                <div class="delete-button mt-3">
                  <%= link_to icon('fa-solid', 'heart'), favourite_path(@favourite),
                  data: {turbo_method: :delete} %>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
        <% if @avg_rating == "No ratings yet" %>
          <h6><b><%= @avg_rating %></b></h6>
        <% else %>
          <div class="card-rating"><h6><b>Rating: </b><%= @avg_rating %> &nbsp</h6>
            <div class="flex gap-x-1 mb-2">
                <% Review::MAX_RATING.times do |n| %>
                  <%# <%= <i class="fa-light fa-star #{star_rating_class(@avg_rating, n)}"></i> %>
                  <%= inline_svg_tag("star.svg",
                    class: "review-star w-8 h-8 #{star_rating_class(@avg_rating, n)}") %>
                <% end %>
            </div>
        <% end %>
            </div>
        <h6>Cuisine:</h6>
        <p><%= @restaurant.cuisine %></p>
        <h6>Description: </h6>
        <p><%= @restaurant.description %></p>
        <h6>Location: </h6>
        <p><%= @restaurant.address %></p>
      </div>

      <div style="width: 100%; height: 600px;"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>

      <div class="review-container">
        <% if user_signed_in? %>
          <div class="review"><h3><b>Reviews</b></h3>
            <% if @reviews.count < 1 %>
              <p>No reviews yet</p>
            <% else %>
              <% @reviews.each do |review| %>
                <div class="reviewer">
                  <% user = review.user %>
                  <%= link_to user_path(user), :action => 'go' do %>
                  <div class="review-avatar">
                    <div class="profile-image" data-action="click->add-profile-image#show">
                      <% if user.photo.attached? %>
                        <%= cl_image_tag user.photo.key, width: 50, height: 50, crop: :thumb, gravity: :face, :class => 'review-profile-pic' %>
                        <% else %>
                        <div class='review-no-profile'>
                        <i class="fa-solid fa-user"></i>
                        </div>
                      <% end %>
                    </div>
                    <h5><%= review.user.name %></h5>
                  </div>
                  <% end %>
                  <div class="description">
                    <h5><b>Rating: </b><%= review.rating %>
                    <br><%= review.comment %></h5>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
          <% else %>
            <span><p><%= link_to "Sign in", new_user_session_path %> to view reviews.</p></span>
          <% end %>
      </div>
      <div class="restaurant-edit">
        <% if user_signed_in? && current_user.role == 'owner' %>
          <p><%= link_to "Edit Restaurant", edit_restaurant_path(@restaurant) %>
          | <%= link_to "Delete",
            restaurant_path(@restaurant),
            data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
          %></p>
        <% elsif user_signed_in? %>
          <button type="button" class="follow-btn" data-bs-toggle="modal" data-bs-target="#exampleModal">
            Add a review
          </button>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%# review form %>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New Review</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@restaurant, @review] do |f| %>
          <%= f.input :comment, input_html: { class: "review-comment-style" } %>
          <%= f.input :rating, collection: [['Terrible', 1], ['Bad', 2], ['Neutral', 3], ['Good', 4], ['Awesome', 5]], label: "Rate your experience", input_html: {data: {controller: "star-rating"}} %>
          <%= f.submit %>
        <% end %>
      </div>
      <%# <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div> %>
    </div>
  </div>
</div>